
AWSTemplateFormatVersion: "2010-09-09"
Description: "Private-only MySQL RDS in a new VPC with private subnets. Identifiers derived from stack name (INSECURE: hardcoded password)."

# Everything hardcoded except identifiers derived from AWS::StackName to allow multiple deployments.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.20.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "hardcoded-private-mysql-vpc"

  # Private route table (no default route to Internet)
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "hardcoded-private-rt"

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1a"         # Change if deploying in another region
      CidrBlock: "10.20.1.0/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "hardcoded-private-a"

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1b"         # Change if deploying in another region
      CidrBlock: "10.20.2.0/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "hardcoded-private-b"

  AssocPrivateSubnetART:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  AssocPrivateSubnetBRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable

  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow MySQL only from within the VPC CIDR"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 3306
          ToPort: 3306
          CidrIp: "10.20.0.0/16"   # Restrict further to app/bastion CIDRs if known
      Tags:
        - Key: Name
          Value: "hardcoded-mysql-sg"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Private DB subnet group for MySQL RDS"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      # Do NOT set DBSubnetGroupName to avoid global name collisions across stacks.

  MySQLDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub "hardcoded-private-mysql-${AWS::StackName}"
      AllocatedStorage: "20"
      StorageType: "gp3"
      DBInstanceClass: "db.t3.micro"
      Engine: "mysql"
      # If this version isn't supported in your region, remove or set to a supported one.
      EngineVersion: "8.0.35"
      MasterUsername: "admin"
      MasterUserPassword: "HardCodedPassword123!"   # INSECURE by design
      PubliclyAccessible: false                      # Enforces private-only
      BackupRetentionPeriod: 7
      MultiAZ: false
      VPCSecurityGroups:
        - !GetAtt MySQLSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      PreferredBackupWindow: "03:00-03:30"
      PreferredMaintenanceWindow: "sun:04:00-sun:04:30"
      AutoMinorVersionUpgrade: true
      DeleteAutomatedBackups: true

Outputs:
  DBEndpointAddress:
    Description: "RDS MySQL endpoint address (resolves to private IPs)"
    Value: !GetAtt MySQLDBInstance.Endpoint.Address
  DBPort:
    Description: "RDS MySQL endpoint port"
    Value: !GetAtt MySQLDBInstance.Endpoint.Port
  DBIdentifier:
    Description: "RDS MySQL instance identifier"
    Value: !Ref MySQLDBInstance
  SecurityGroupId:
    Description: "Security Group ID allowing MySQL from VPC CIDR"
    Value: !GetAtt MySQLSecurityGroup.GroupId
  SubnetGroupName:
    Description: "DB Subnet Group Name"
    Value: !Ref DBSubnetGroup
