
version: 0.2

phases:
  install:
    commands:
      - echo "Preparing environment..."
      - yum install -y jq || true

  pre_build:
    commands:
      - echo "Validating repository structure..."
      - ls -la
      - test -f scripts/deploy.sh || (echo "scripts/deploy.sh missing"; exit 1)
      - test -f connectorA/template.yaml || (echo "connectorA/template.yaml missing"; exit 1)
      - test -f connectorB/template.yaml || (echo "connectorB/template.yaml missing"; exit 1)
      - test -f connectorC/template.yaml || (echo "connectorC/template.yaml missing"; exit 1)

  build:
    commands:
      - echo "Starting deployment for all connectors"
      - chmod +x scripts/deploy.sh
      - ./scripts/deploy.sh "connectorA connectorB connectorC"

artifacts:
  files:
    - "**/*"
