version: 0.2

phases:
  install:
    commands:
      - echo "Preparing environment..."
      - |
        if command -v yum >/dev/null 2>&1; then
          sudo yum install -y jq || true
          sudo yum install curl -y
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          source ~/.bashrc
          source ~/.bash_profile
          
          # Use modern Node that satisfies undici@7 (prefer 22 LTS)
          nvm install --lts
          nvm use --lts
          nvm alias default 'lts/*'
          
          # (Optional) keep global npm installs under your home (no sudo required)
          npm config set prefix "$HOME/.npm-global"
          export PATH="$HOME/.npm-global/bin:$PATH"
          echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.bashrc
          
          # Sanity check: ensure node/npm are from NVM (not /usr/bin or /usr/local/bin)
          echo "node: $(which node) -> $(node -v)"
          echo "npm:  $(which npm)  -> $(npm -v)"
          
          # Install Bruno CLI
          npm install -g @usebruno/cli
          
          # Verify
          bru --version || bruno --version

         
          
        elif command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update -y || true
          sudo apt-get install -y jq || true
          sudo apt install curl build-essential -y
          
          # Explicitly set NVM_DIR and run installation script
          export NVM_DIR="$HOME/.nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
          
          # Load NVM into the current running script/shell using POSIX '.'
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm functions
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # Load bash_completion
          node -v
          npm -v
          
          npm cache clean --force
         


          

        else
          echo "No supported package manager found; skipping jq install"
        fi

  pre_build:
    commands:
      - echo "Validating repository structure..."
      - npm install -g @usebruno/cli
      - bru --version
      - ls -la
      - test -f scripts/deploy.sh || (echo "scripts/deploy.sh missing"; exit 1)
      - test -f connectorA/template.yml || (echo "connectorA/template.yml missing"; exit 1)
      - test -f connectorB/template.yml || (echo "connectorB/template.yml missing"; exit 1)
      - test -f connectorC/template.yml || (echo "connectorC/template.yml missing"; exit 1)

  build:
    commands:
      - chmod +x scripts/deploy.sh
      - ./scripts/deploy.sh "connectorA connectorB connectorC"

artifacts:
  files:

    - "**/*"












