version: 0.2

phases:
  install:
    commands:
      - echo "Preparing environment..."
      - |
        if command -v yum >/dev/null 2>&1; then
          sudo yum install -y jq || true
        elif command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update -y || true
          sudo apt-get install -y jq || true
        else
          echo "No supported package manager found; skipping jq install"
        fi

  pre_build:
    commands:
      - echo "Validating repository structure..."
      - ls -la
      - test -f scripts/deploy.sh || (echo "scripts/deploy.sh missing"; exit 1)
      - test -f connectorA/template.yaml || (echo "connectorA/template.yaml missing"; exit 1)
      - test -f connectorB/template.yaml || (echo "connectorB/template.yaml missing"; exit 1)
      - test -f connectorC/template.yaml || (echo "connectorC/template.yaml missing"; exit 1)

  build:
    commands:
      - echo "Starting deployment for: connectorA connectorB connectorC"
      - chmod +x scripts/deploy.sh
      - ./scripts/deploy.sh "connectorA connectorB connectorC"

artifacts:
  files:
    - "**/*"