
AWSTemplateFormatVersion: "2010-09-09"
Description: "Fully-private MySQL RDS in a new VPC with private subnets and VPC endpoints. All values hardcoded; identifiers derived from AWS::StackName. (INSECURE: hardcoded password)."

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.20.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "hardcoded-private-mysql-vpc"

  # Private route table with NO 0.0.0.0/0 route (no IGW/NAT)
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "hardcoded-private-rt"

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1a"    # Hardcoded region/AZs
      CidrBlock: "10.20.1.0/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "hardcoded-private-a"

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.20.2.0/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "hardcoded-private-b"

  AssocPrivateSubnetART:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable

  AssocPrivateSubnetBRT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable

  # Security group for application clients that are allowed to connect to MySQL
  AppClientSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "App clients allowed to connect to private MySQL"
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "10.20.0.0/16"  # Internal egress within VPC only
      Tags:
        - Key: Name
          Value: "hardcoded-app-client-sg"

  # MySQL SG only allows 3306 from the AppClientSecurityGroup
  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow MySQL only from AppClientSecurityGroup"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppClientSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "10.20.0.0/16"  # Internal egress within VPC only
      Tags:
        - Key: Name
          Value: "hardcoded-mysql-sg"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Private DB subnet group for MySQL RDS"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB

  MySQLDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub "hardcoded-private-mysql-${AWS::StackName}"
      AllocatedStorage: "40"
      StorageType: "gp3"
      DBInstanceClass: "db.t3.micro"
      Engine: "mysql"
      EngineVersion: "8.0.44"               # Hardcoded version
      MasterUsername: "admin"               # Hardcoded username
      MasterUserPassword: "HardCodedPassword123!"  # INSECURE: Hardcoded
      PubliclyAccessible: false             # Private-only endpoint
      BackupRetentionPeriod: 7
      MultiAZ: false
      VPCSecurityGroups:
        - !GetAtt MySQLSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      PreferredBackupWindow: "03:00-03:30"
      PreferredMaintenanceWindow: "sun:04:00-sun:04:30"
      AutoMinorVersionUpgrade: true
      DeleteAutomatedBackups: true
      StorageEncrypted: true                # Uses AWS-managed key for RDS

  # --- VPC Endpoints to keep client traffic private (no IGW/NAT required) ---

  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: "com.amazonaws.us-east-1.s3"
      VpcEndpointType: "Gateway"
      RouteTableIds:
        - !Ref PrivateRouteTable
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:*"
            Resource: "*"

  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: "com.amazonaws.us-east-1.secretsmanager"
      VpcEndpointType: "Interface"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      SecurityGroupIds:
        - !Ref AppClientSecurityGroup
      PrivateDnsEnabled: true

  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: "com.amazonaws.us-east-1.logs"
      VpcEndpointType: "Interface"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      SecurityGroupIds:
        - !Ref AppClientSecurityGroup
      PrivateDnsEnabled: true

  KMSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: "com.amazonaws.us-east-1.kms"
      VpcEndpointType: "Interface"
      SubnetIds:
        - !Ref PrivateSubnetA
        - !Ref PrivateSubnetB
      SecurityGroupIds:
        - !Ref AppClientSecurityGroup
      PrivateDnsEnabled: true

Outputs:
  DBEndpointAddress:
    Description: "RDS MySQL endpoint address (private DNS)"
    Value: !GetAtt MySQLDBInstance.Endpoint.Address
  DBPort:
    Description: "RDS MySQL endpoint port"
    Value: !GetAtt MySQLDBInstance.Endpoint.Port
  DBIdentifier:
    Description: "RDS MySQL instance identifier"
    Value: !Ref MySQLDBInstance
  MySQLSecurityGroupId:
    Description: "MySQL Security Group ID"
    Value: !GetAtt MySQLSecurityGroup.GroupId
  AppClientSecurityGroupId:
    Description: "App Client Security Group ID"
    Value: !GetAtt AppClientSecurityGroup.GroupId
  SubnetGroupName:
    Description: "DB Subnet Group Name"
    Value: !Ref DBSubnetGroup
